#!/bin/bash
# 
# gsas_current_wtfrac - extract current weight fraction of a phase
# (C) Sven Vogel, sven@lanl.gov
#
# call
#
# gsas_current_wtfrac <phase>
#
# phase - the phase for which the weight fraction is extracted
#

# Check syntax
if [ "$1" = "" ]; then
	echo "$0 called without a phase number!"
	read -p "You should abort here, please hit Ctrl-C."
	exit 0
fi

grep "Wt." `cat GSAS_EXP`.LST > temp.txt
if [ $? -ne 0 ]; then
	if [ "$2" != "ignore_not_refined" ]; then
	    echo "Could not find wt. fraction in current LST file - maybe it was not refined yet?"
	    read -p "You should abort here, please hit Ctrl-C."
	fi
	exit 0
fi

grep "EXPR NPHAS" `cat GSAS_EXP`.EXP | awk '{print $3+$4+$5+$6+$7+$8+$9+$10+$11}' > temp.txt
num_phases=`gsas_get_number_of_phases`
num_hist=`gsas_get_number_of_histograms`
let phase=$1
let lines_per_phase=$num_hist/7+1
let modulus=$num_hist%7
if [ $modulus -eq 0 ]; then
  let lines_per_phase=$lines_per_phase-1
fi
let lines_for_this_phase=$lines_per_phase*$phase
let lines_for_total_block=$lines_per_phase*$num_phases

# echo "Phase requested: <$phase>"
# echo "Number of phases in refinement: <$num_phases>"
# echo "Number of histograms in refinement: <$num_hist>"
# echo "Number of lines with wt. fractions per phase in LST file: <$lines_per_phase>"
# echo "Modulus: <$modulus>"
# echo "Lines for block of current weight fractions: <$lines_for_total_block>"
# echo "Last line for this phase: <$lines_for_this_phase>"
grep "Wt." `cat GSAS_EXP`.LST | tail -n $lines_for_total_block | head -n $lines_for_this_phase | tail -n 1 | awk '{print $3}' > temp.txt
# output weight fraction, so the calling process can read it
awk '{printf("%.5f\n", +$1)  }' <  temp.txt


