#!/bin/bash
# 
# gsas_get_bank_for_histogram - extract the bank number of a histogram
# (C) Sven Vogel, sven@lanl.gov
#
# call
#
# gsas_get_bank_for_histogram <bank>
#
# bank - a bank number found in the current EXP file
#

# Check syntax
# nothing to do

grep "$1 BANK " `cat GSAS_EXP`.EXP | awk '{print $3+$4+$5+$6+$7+$8+$9+$10+$11}' > temp.txt
# output number of phases, so the calling process can read it
cat temp.txt


