#!/bin/bash
# echo the call so we can see what's going on
echo "$0 $1 $2 $3 $4 $5 $6"

# Check syntax
if [ "$1" = "" ]; then
	echo "$0 called without number of histogram for which sigma1 should be changed!"
	exit 0
fi

if [ "$2" = "" ]; then
	echo "$0 called without number phase for which sigma1 should be changed!"
	exit 0
fi

if [ "$3" = "" ]; then
	echo "$0 called without value for sigma0!"
	exit 0
fi

if [ "$4" = "" ]; then
	echo "$0 called without value for sigma1!"
	exit 0
fi

if [ "$5" = "" ]; then
	echo "$0 called without value for sigma2!"
	exit 0
fi

# Change the flags
echo "k l o p" > temp.txt
echo "h $1" >> temp.txt
echo "p $2" >> temp.txt
echo "c" >> temp.txt
echo "/" >> temp.txt 
echo "/" >> temp.txt 
echo "$3 $4 $5" >> temp.txt 
echo "/" >> temp.txt 
echo "/" >> temp.txt
echo "l" >> temp.txt
echo "x" >> temp.txt
echo "x" >> temp.txt
echo "x" >> temp.txt
echo "x" >> temp.txt

expedt `cat GSAS_EXP` < temp.txt > out.txt

# Test the EXP file
echo "Changed sigma values for histogram $1 and phase $2 to $3, $4 and $5.\newline" >> temp.tex
