#!/bin/bash
# echo the call so we can see what's going on
echo "$0 $1 $2 $3 $4 $5 $6"

# Check syntax
if [ "$1" = "" ]; then
	echo "$0 called without number of histogram for which DIFC variation flags should be changed!"
	exit 0
fi

if [ "$2" = "" ]; then
	echo "$0 called without DIFC refinement flags!"
	exit 0
fi

# Change the flags
echo "k l o c" > temp.txt
echo "h $1" >> temp.txt
echo "v $2" >> temp.txt
if [ "$3" != "" ]; then
	echo "$0 called with new damping flag, changing it!"
	echo "d $3" >> temp.txt
fi
echo "x" >> temp.txt
echo "x" >> temp.txt
echo "x" >> temp.txt
echo "x" >> temp.txt

expedt `cat GSAS_EXP` < temp.txt

# Test the EXP file
echo "Changed DIFC refinement flags for histogram $1 to \verb=$2=.\newline" >> temp.tex
